  default:
    dockerimage: ubuntu:trusty
    build_steps:
      - apt-get update && apt-get -y install wget unzip nginx ca-certificates php5 php5-fpm php5-cli php5-json php5-mysql php5-curl php5-sqlite
      - ENV PAGEKIT_VERSION 1.0.3
      - mkdir /pagekit
      - cd /pagekit
      - wget https://github.com/pagekit/pagekit/releases/download/1.0.3/pagekit-1.0.3.zip
      - unzip pagekit-1.0.3.zip
      - ADD nginx.conf /etc/nginx/nginx.conf
      - apt-get autoremove -y && apt-get autoclean -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      - chown -R www-data: /pagekit
    run_steps: 
      - service php5-fpm start
      - service nginx start
